version: "3.9"

services:
  db:
    image: postgres:latest
    env_file:
      - pg.env
    ports:
      - "5432:5432"
    volumes:
      - ./sql/model.sql:/docker-entrypoint-initdb.d/init.sql
  nats:
    image: nats-streaming:latest
    ports:
      - "4222:4222"

  nats-ui:
    image: piotrpersona/nats-streaming-ui:latest
    ports:
      - "8282:8282"
    environment:
      STAN_URL: "http://nats:4222"
      STAN_MONITOR_URL: "http://nats:8222"
      STAN_CLUSTER: test-cluster
